classDiagram
direction TB
    class Lanchonete {
	    ~~~interface~
	    +String Nome
	    +String Unidade
	    +String Predio
	    +String linkMapa
    }

    class LanchonetesInfoComponent {
	    -ActivatedRoute route
	    +Lanchonete lanchoneteDetalhes
	    +any[] itens
	    +ngOnInit()
	    +getPreco(item, nomeLanchonete)
    }

    class LanchonetesComponent {
	    -Router router
	    +String searchTerm
	    +any[] lanchonetes
	    +lanchonetesFiltradas
	    +search(e)
	    +trackById(index, lanchonete)
	    +voltar()
    }

    class CompararPrecosComponent {
	    -CompararPrecosService compararPrecosService
	    +any[] itens
	    +any[] lanchonetes
	    +modoVisualizacao: 'alfabetica' | 'precoMedio'
	    +String itemSelecionado
	    +String lanchoneteComMenorPreco
	    +String lanchoneteMenorMedia
	    +number menorPreco
	    +ngOnInit()
	    +toggleModoVisualizacao()
	    +destacarItem(event)
	    +isMenorPreco(item, lanchonete)
	    +isLanchonete(lanchonete)
    }

    class CompararPrecosService {
	    +calcularPrecoMedio(item, lanchonetes)
	    +getPreco(item, nomeLanchonete)
	    +calcularLanchoneteComMenorMedia(itens, lanchonetes)
      +calcularLanchoneteComMenorPreco(itens, lanchonetes)
      +ordenarItens(itens, modo, lanchonetes)
      +getItemId(item)
    }

    class ActivatedRoute {
    }

    class Router {
    }

    LanchonetesInfoComponent ..> "1" ActivatedRoute
    LanchonetesInfoComponent ..|> "*" Lanchonete
    CompararPrecosComponent ..|> "*" Lanchonete
    LanchonetesComponent ..> "1" Router
    LanchonetesComponent ..|> "*" Lanchonete
    CompararPrecosComponent --> "1" CompararPrecosService

